### ISSUE TITLE
Suggested Rockon for DNS Service Automation

### ISSUE THREAD

**Issue by thailgrott** [rockstor/rockon-registry#136]
The phesley docker-dns-rest gives a container with a rest API to automatically build DNS for the docker containers. This would be useful for configuring other docker containers with host names, instead of by IP or manually keeping a primary DNS for the zone.

 https://github.com/phensley/docker-dns-rest

While trying to translate the docker command to the needed Rockon json. 
```
docker run -d -p 5080:80 -v /var/run/docker.sock:/docker.sock --name dns \
    phensley/docker-dns-rest --verbose 
```
The following JSON is what I've come up with. And when I just run the above docker command the container starts up just fine. Although, when I install it with the JSON below as a Rockon the container just continually restarts. 

```
{
  "Phensley docker-dns-rest": {
    "description": "Container DNS rest API",
    "version": "0.1",
    "website": "https://github.com/phensley/docker-dns-rest",
    "containers": {
      "DNS_Rest_API": {
        "image": "phensley/docker-dns-rest",
        "tag": "latest",
        "launch_order": 1,
        "ports": {
          "80": {
            "description": "The port used for the rest API DNS managment",
            "host_default": 2053,
            "label": "Rest API",
            "protocol": "tcp",
            "ui": false
          }
        },
        "opts": [
          ["--net", "host"],
          ["-v", "/var/run/docker.sock:/docker.sock"]
        ]
      }
    }
  }
}
```

```
2017-11-10T21:23:57.751613000Z Traceback (most recent call last):
2017-11-10T21:23:57.752015000Z   File "/data/docker_dnsrest", line 106, in <module>
2017-11-10T21:23:57.752479000Z     main()
2017-11-10T21:23:57.752678000Z   File "/data/docker_dnsrest", line 95, in main
2017-11-10T21:23:57.752869000Z     api.start()
2017-11-10T21:23:57.753057000Z   File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 234, in start
2017-11-10T21:23:57.753249000Z     self.init_socket()
2017-11-10T21:23:57.753461000Z   File "/usr/lib/python2.7/site-packages/gevent/pywsgi.py", line 639, in init_socket
2017-11-10T21:23:57.753648000Z     StreamServer.init_socket(self)
2017-11-10T21:23:57.753835000Z   File "/usr/lib/python2.7/site-packages/gevent/server.py", line 78, in init_socket
2017-11-10T21:23:57.754025000Z     self.socket = self.get_listener(self.address, self.backlog, self.family)
2017-11-10T21:23:57.754216000Z   File "/usr/lib/python2.7/site-packages/gevent/server.py", line 89, in get_listener
2017-11-10T21:23:57.754410000Z     return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
2017-11-10T21:23:57.754598000Z   File "/usr/lib/python2.7/site-packages/gevent/server.py", line 153, in _tcp_listener
2017-11-10T21:23:57.754783000Z     sock.bind(address)
2017-11-10T21:23:57.754971000Z   File "<string>", line 1, in bind
2017-11-10T21:23:57.755158000Z socket.error: [Errno 98] Address in use: ('0.0.0.0', 80)

```

**Comment by magicalyak** [comment]
One option honestly might be installing webmin on the box itself. You could install bind, bind-utils and dhcp and get to manage dns and dhcp from the url console.  I haven't tried this though.

**Comment by phillxnet** [comment]
@FroggyFlox Sorry to flag yet another issue but I'm thinking this may relate to your ongoing enhancements re docker networking, in which case we could link it for context.

**Comment by Hooverdan96** [comment]
Since we never resolved this issue, and that container was last tended to 4 years ago, I propose we close this issue and see whether a different one with similar functionality re DNS is currently actively maintained/offered, if the community is interested.
