### ISSUE TITLE
Jellyfin ROCKON Install Wizard is empty

### ISSUE THREAD

**Issue by stefanogreg** [rockstor/rockon-registry#340]
I tried to install Jellyfin from ROCKONS but the installation wizard seems to be empty, no error appear
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/6837406/203421161-a4fb044f-d367-4abb-80c6-87225d1335d2.png">

Here Logs from Browser console the error happen when clicking the Install button
jquery-1.9.1.min.js:5          GET https://192.168.1.31/api/rockons/devices/52?page=1&format=json&page_size=32000&count= 500 (Internal Server Error)

In the Logs the issue seems connected to the fact that I have two USB disks connected and one does not support SMART commands - those disks do not have BTRFS Partition and are used to backup stuff via RSYNC

here the Rockstor logs:
[22/Nov/2022 22:09:04] ERROR [storageadmin.middleware:33] Exception occurred while processing a request. Path: /api/rockons/devices/52 method: GET
[22/Nov/2022 22:09:04] ERROR [storageadmin.middleware:34] (u"Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the RockOnDeviceSerializer serializer.",)
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.11.29-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.11.29-py2.7.egg/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.9.3-py2.7.egg/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.9.3-py2.7.egg/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.9.3-py2.7.egg/rest_framework/views.py", line 466, in raise_uncaught_exception
    raise exc
AssertionError: (u"Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the RockOnDeviceSerializer serializer.",)
[22/Nov/2022 22:09:14] ERROR [storageadmin.views.disk:479] Error running a command. cmd = /usr/sbin/smartctl --info /dev/disk/by-id/usb-Seagate_Expansion_NAAR8LHJ-0:0. rc = 2. stdout = ['smartctl 7.2 2021-09-14 r5237 [x86_64-linux-5.3.18-150300.59.101-default] (SUSE RPM)', 'Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org', '', 'Read Device Identity failed: scsi error unsupported field in scsi command', '', "A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.", '']. stderr = ['']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 476, in _update_disk_state
    do.name, do.smart_options
  File "/opt/rockstor/src/rockstor/system/smart.py", line 338, in available
    [SMART, "--info"] + get_dev_options(device, custom_options)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 225, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /usr/sbin/smartctl --info /dev/disk/by-id/usb-Seagate_Expansion_NAAR8LHJ-0:0. rc = 2. stdout = ['smartctl 7.2 2021-09-14 r5237 [x86_64-linux-5.3.18-150300.59.101-default] (SUSE RPM)', 'Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org', '', 'Read Device Identity failed: scsi error unsupported field in scsi command', '', "A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.", '']. stderr = ['']
[22/Nov/2022 22:10:16] ERROR [storageadmin.views.disk:479] Error running a command. cmd = /usr/sbin/smartctl --info /dev/disk/by-id/usb-Seagate_Expansion_NAAR8LHJ-0:0. rc = 2. stdout = ['smartctl 7.2 2021-09-14 r5237 [x86_64-linux-5.3.18-150300.59.101-default] (SUSE RPM)', 'Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org', '', 'Read Device Identity failed: scsi error unsupported field in scsi command', '', "A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.", '']. stderr = ['']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 476, in _update_disk_state
    do.name, do.smart_options
  File "/opt/rockstor/src/rockstor/system/smart.py", line 338, in available
    [SMART, "--info"] + get_dev_options(device, custom_options)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 225, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /usr/sbin/smartctl --info /dev/disk/by-id/usb-Seagate_Expansion_NAAR8LHJ-0:0. rc = 2. stdout = ['smartctl 7.2 2021-09-14 r5237 [x86_64-linux-5.3.18-150300.59.101-default] (SUSE RPM)', 'Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org', '', 'Read Device Identity failed: scsi error unsupported field in scsi command', '', "A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.", '']. stderr = ['']

**Comment by stefanogreg** [comment]
The previous logs probably are not related to the issue reported, I was able to install other ROCKONS which require Storage selection

**Comment by FroggyFlox** [comment]
Hi @stefanogreg ,

Thanks for reporting this. This sort of report usually is better suited for our forum as it gets a lot more exposure and thus has a better chance at finding a fix.
As a matter of fact, a forum user just reported what I believe is the same problem than you. Thanks a lot for including the logs, by the way as that is a very big clue.
See the following forum post and the its answers:
https://forum.rockstor.com/t/unknown-client-error-doing-a-get-to-api-rockons-devices-152/7661/13?u=flox

I apologize for the very brief answer here but I'm on my phone and it's not the most convenient for me; I still wanted to guide you towards that answer on the forum.

You are correct with regards to the USB devices not supporting SMART: this is actually a normal error as it just indicates that these drives do not support that.

Hope this helps,

**Comment by Hooverdan96** [comment]
@stefanogreg hope all is well. Wanted to check in whether you were able to resolve your issue and this entry can be closed?
