### ISSUE TITLE
Duplicati fails to install

### ISSUE THREAD

**Issue by alazare619** [rockstor/rockon-registry#78]
Duplicati fails to install on a fresh install of rockstor..I'll attempt to get logs.

**Comment by alazare619** [comment]
`[24/Jan/2017 08:25:59] DEBUG [storageadmin.views.rockon_helpers:62] Attempted to remove a container(duplicati2-canary). out: [''] err: ['Cannot connect to the Docker daemon. Is the docker daemon running on this host?', 'Error: failed to remove containers: [duplicati2-canary]', ''] rc: 1.
[24/Jan/2017 08:25:59] DEBUG [storageadmin.views.rockon_helpers:123] exception while installing the Rockon(39)
[24/Jan/2017 08:25:59] ERROR [storageadmin.views.rockon_helpers:124] Error running a command. cmd = ['/usr/bin/docker', 'run', '-d', '--restart=unless-stopped', '--name', 'duplicati2-canary', '-v', '/mnt2/rockon-config-duplicati:/root/.config/Duplicati/', '-v', '/etc/localtime:/etc/localtime:ro', '-p', '8200:8200/tcp', '-e', 'MONO_EXTERNAL_ENCODINGS=UTF-8', '-e', 'DUPLICATI_PASS=Neolithica414619!', 'intersoftlab/duplicati']. rc = 1. stdout = ['']. stderr = ['Cannot connect to the Docker daemon. Is the docker daemon running on this host?', '']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 121, in install
    generic_install)(rockon)
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 219, in generic_install
    run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 109, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = ['/usr/bin/docker', 'run', '-d', '--restart=unless-stopped', '--name', 'duplicati2-canary', '-v', '/mnt2/rockon-config-duplicati:/root/.config/Duplicati/', '-v', '/etc/localtime:/etc/localtime:ro', '-p', '8200:8200/tcp', '-e', 'MONO_EXTERNAL_ENCODINGS=UTF-8', '-e', 'DUPLICATI_PASS=Neolithica414619!', 'intersoftlab/duplicati']. rc = 1. stdout = ['']. stderr = ['Cannot connect to the Docker daemon. Is the docker daemon running on this host?', '']
[24/Jan/2017 08:26:00] ERROR [storageadmin.util:44] exception: Docker service is not running. Start it and try again.
Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-0.16.1-py2.7.egg/gunicorn/workers/sync.py", line 34, in run
    client, addr = self.socket.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
[24/Jan/2017 08:26:00] DEBUG [storageadmin.util:45] Current Rockstor version: 3.8.16-8
[24/Jan/2017 08:26:06] DEBUG [storageadmin.views.rockon_helpers:62] Attempted to remove a container(duplicati2-canary). out: [''] err: ['Cannot connect to the Docker daemon. Is the docker daemon running on this host?', 'Error: failed to remove containers: [duplicati2-canary]', ''] rc: 1.
[24/Jan/2017 08:26:06] DEBUG [storageadmin.views.rockon_helpers:123] exception while installing the Rockon(39)
[24/Jan/2017 08:26:06] ERROR [storageadmin.views.rockon_helpers:124] Error running a command. cmd = ['/usr/bin/docker', 'run', '-d', '--restart=unless-stopped', '--name', 'duplicati2-canary', '-v', '/mnt2/rockon-config-duplicati:/root/.config/Duplicati/', '-v', '/etc/localtime:/etc/localtime:ro', '-p', '8200:8200/tcp', '-e', 'MONO_EXTERNAL_ENCODINGS=UTF-8', '-e', 'DUPLICATI_PASS=Neolithica414619!', 'intersoftlab/duplicati']. rc = 1. stdout = ['']. stderr = ['Cannot connect to the Docker daemon. Is the docker daemon running on this host?', '']
Traceback (most recent call last):`
